version: "3.9"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432"
  webapp:
    build: .
    image: slap:1.0
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -e production -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/slap
    ports:
      - "3000:3000"
    depends_on:
      - db
